ALTER TYPE "InstallationIssueType" ADD VALUE IF NOT EXISTS 'INSTALLATION_AUTOMATION_FAILED';
ALTER TYPE "InstallationIssueType" ADD VALUE IF NOT EXISTS 'INSTALLATION_WORKFLOW_ORPHANED';
ALTER TYPE "InstallationNotificationStatus" ADD VALUE IF NOT EXISTS 'UNKNOWN';

ALTER TABLE "installation_notifications"
  ADD COLUMN IF NOT EXISTS "delivery_check_count" INTEGER NOT NULL DEFAULT 0;
